// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_FpRDCciSAb23OsZKun9pgCZhsvaD1c',
    appId: '1:35198981376:web:79adddea8171e46c33cfe5',
    messagingSenderId: '35198981376',
    projectId: 'flutter-crud-app2',
    authDomain: 'flutter-crud-app2.firebaseapp.com',
    storageBucket: 'flutter-crud-app2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqc1MAPOLZXwViJ95H4SgBBcRU3x_ckc',
    appId: '1:35198981376:android:9d7b22a7f8cad28433cfe5',
    messagingSenderId: '35198981376',
    projectId: 'flutter-crud-app2',
    storageBucket: 'flutter-crud-app2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEmTYIv9PJNmE-io9Jh5ZwASFJlhnwB6w',
    appId: '1:35198981376:ios:f5e88eb2c4e11daf33cfe5',
    messagingSenderId: '35198981376',
    projectId: 'flutter-crud-app2',
    storageBucket: 'flutter-crud-app2.appspot.com',
    iosClientId: '35198981376-m0ggraq26i0a481jdqacc99rrnvtlm0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firenaseCrud2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEmTYIv9PJNmE-io9Jh5ZwASFJlhnwB6w',
    appId: '1:35198981376:ios:f5e88eb2c4e11daf33cfe5',
    messagingSenderId: '35198981376',
    projectId: 'flutter-crud-app2',
    storageBucket: 'flutter-crud-app2.appspot.com',
    iosClientId: '35198981376-m0ggraq26i0a481jdqacc99rrnvtlm0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firenaseCrud2',
  );
}
